### ISSUE TITLE
CollapseTransition please

### ISSUE THREAD

**Issue by zuo305** [Noction/vue-bezier#2]
Hi @50rayn thanks for the lib update to vue3, I am just wondering when the "CollapseTransition" will be published and what bug is it now. Maybe I can give some help.

**Comment by 50rayn** [comment]
Hello @zuo305 .
I have just release [v.1.0.4](https://github.com/50rayn/vue3-sfc-transitions/releases/tag/v.1.0.4).
I have done a more detailed research on this transition component and realised that the problem itself was in the documentation.

P.S. Thanks a lot for your contribution and feedback. If any other issues will be discovered, fill free :). 
P.P.S. I'll wait your confirmation that everything is ok, then I'll close the issue :)
