### ISSUE TITLE
Add web-types for better webstorm integration

### ISSUE THREAD

**Issue by LwveMike** [Noction/vue-bezier#3]
Please add web-types for a better webstorm integration. This will add autocomplete to props and webstorm will understand that the component is registered globally.
At the moment, webstorm doesn't recognise global registered components and gives "Unknown html tag slide-y-down-transition " warning.

![image](https://github.com/50rayn/vue3-sfc-transitions/assets/51880748/5a48ca52-1ac2-4ba4-a169-9017079d0e26)

**Comment by 50rayn** [comment]
Web-types were added in version [v1.0.5](https://github.com/Noction/vue-bezier/releases/tag/v1.0.5)

**Comment by 50rayn** [comment]
Web-types were added in version [v1.0.5](https://github.com/Noction/vue-bezier/releases/tag/v1.0.5)
